site_name: The Ultimate Guide To AoE2DE UGC
docs_dir: docs/
repo_name: "AoE2DE_UGC_Guide"
repo_url: "https://github.com/Divy1211/AoE2DE_UGC_Guide"

nav:
  - About: "index.md"
  - Game Mechanics:
    - Damage Calculation: "general/damage_calculation.md"
    - Attributes: "general/attributes.md"
    - Resources: "general/resources/resources.md"
    - Hotkeys: "general/hotkeys/hotkeys.md"
  - Custom Scenarios:
    - Scenario Basics: "scenarios/basics.md"
    - Triggers:
      - Trigger Basics: "scenarios/triggers/basics.md"
      - Effects: "scenarios/triggers/effects/effects.md"
    #   - Conditions: "scenarios/triggers/conditions/conditions.md"
    #   - Variables: "scenarios/triggers/variables.md"
    # - Tricks and Tips: "scenarios/tricks.md"
    # - Advanced:
    #   - File Byte Structure: "scenarios/advanced/byte_structure.md"
    - Useful Tools:
      # - Advanced Genie Editor:
      #   - A.G.E. Uses: "scenarios/useful_tools/age/uses.md"
      #   - Unhiding Editor Units: "scenarios/useful_tools/age/unhide.md"
      - AoE2ScenarioParser:
        - Parser Basics: "scenarios/useful_tools/parser/basics.md"
  - XS Scripting: 
    - For Beginners: "general/xs/beginner.md"
    - For Programmers: "general/xs/programmer.md"
    - Functions Reference: "general/xs/functions.md"
    - Constant Reference: "general/xs/constants.md"
    - Known Bugs: "general/xs/bugs.md"
#   - Data Mods:
#     - Data Mod Basics: "data_mods/basics.md"
#     - Advanced Genie Editor:
#       - A.G.E. Basics: "data_mods/age/basics.md"
#   - RMS:
#     - RMS Basics: "rms/basics.md"
# - Publishing UGC: "publishing_ugc/publish.md"

markdown_extensions:
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - pymdownx.caret # handling sub- and superscripts
  - pymdownx.mark # highlighting of text
  - pymdownx.tilde # strikethrough of text
  - pymdownx.keys # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys
  - pymdownx.tabbed # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#tabbed
  - pymdownx.details # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#details
  - pymdownx.highlight: # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#superfences
  - pymdownx.smartsymbols # supporting special characters like copyright symbol (c)
  - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/mathjax/#arithmatex
      generic: true
  - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/#tasklist
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      separator: '[\s\-\.\_]+'

extra_css:
  - style.css

theme:
  name: material
  language: en
  favicon: imgs/code.svg
  icon:
    logo: fontawesome/solid/code
  features:
    - navigation.tabs
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    # - navigation.sections
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Roboto Slab
    code: Source Code Pro
